apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}
data:
  mosquitto.conf: |-
    allow_anonymous   false
    listener          1883
    password_file     /mosquitto/passwd
