apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}-lb
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
